import React from "react";
import { Link } from "react-router-dom";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import "./Products.css";

const benefits = ["Online platform for nonprofits and organizations","Connect with philanthropists meaningfully","Create visually compelling campaigns","Raise awareness and funding efficiently","Build stronger communities","Celebrate your social causes"];
export default function Products() { return <main className="products-page">
  <section className="products-hero"><div className="network"/><div><h1>Our products and investments</h1><p>Innovative solutions designed to create meaningful impact and connect<br/>communities</p></div></section>
  <section className="powered products-wrap"><div className="hand-art"><span>●</span></div><div><h2>Powered by<br/>Innovation</h2><p>We leverage cutting-edge technology and artificial intelligence to create products that make a real difference in how organizations connect, collaborate, and create impact.</p><p>Our solutions are designed with the future in mind, combining powerful features with intuitive interfaces to deliver exceptional user experiences.</p></div></section>
  <section className="socialbirds"><div className="products-wrap"><span className="product-tag">◦ Create An Initiative</span><h2><em>Social</em>Birds Platform</h2><a className="visit-button" href="https://socialbirds.com" target="_blank" rel="noreferrer">Visit Website <ArrowForwardIcon/></a><div className="bird-content"><div><p>SocialBirds is an online platform providing help to organizations to achieve their objectives. Many social organizations are working to help their communities, however with the increasing social media there is a potential opportunity to quickly reach out and engage larger philanthropists in a meaningful way.</p><p>To fulfill the need, we set off to build SocialBirds online platform that would connect more people with more nonprofits organizations in a more meaningful way. SocialBirds Teams has taken extra steps to create a stronger community of like-minded people dedicated to celebrating youth for their social causes.</p><p>In our effort to empower organizations existing fundraising and volunteering activities by giving you a user-friendly online platform for create visually compelling campaigns that raise awareness and funding for your organizational needs and dreams.</p></div><div className="socialbirds-logo">S <b>Social</b>Birds</div></div><h3>Key Benefits</h3><div className="benefit-pills">{benefits.map(item=><span key={item}>◉ &nbsp;{item}</span>)}</div><div className="bird-cards">{[["♧","Community Building","Meaningful organizations and nonprofits working together"],["♞","Campaign Creation","Create visually compelling campaigns that focus on awareness and funding"],["♡","Social Impact","Connect with and empower philanthropists through your causes"],["⌁","Fundraising Tools","Implement effective fundraising campaigns and strategies"]].map(([icon,title,text])=><article key={title}><span>{icon}</span><h4>{title}</h4><p>{text}</p></article>)}</div></div></section>
  <section className="hireko"><div className="products-wrap"><span className="product-tag blue">◦ AI Recruitment</span><h2>Hireko.ai</h2><a className="visit-button blue-btn" href="#hireko">Visit Website <ArrowForwardIcon/></a><div><div className="hireko-logo">♨ Hi.reko.<b>ai</b></div><div className="hireko-copy"><p>Hireko.ai is revolutionizing enterprise recruitment with AI-powered interview solutions. Our advanced platform streamlines the hiring process by conducting intelligent, automated interviews that assess candidates comprehensively and objectively.</p><p>By leveraging cutting-edge artificial intelligence and natural language processing, Hireko.ai helps enterprises save time, reduce bias, and identify the best talent efficiently. The platform provides detailed insights and analytics to make informed hiring decisions.</p><p>As an investment by Dwaith Infotech, Hireko.ai represents our commitment to supporting innovative AI solutions that transform traditional business processes and drive meaningful impact in the enterprise space.</p></div></div></div></section>
  <section className="future"><div className="products-wrap"><span className="product-tag">◦ Future Investments</span><h2>Revolutionizing Impact</h2><p>Our development team is hard at work creating new products and services that will revolutionize<br/>how organizations connect, collaborate, and create meaningful impact.</p><div className="robot-hand">AI</div><p className="future-note">Our AI-powered solutions are designed to transform how you work,<br/>collaborate, and achieve your goals. Stay tuned for groundbreaking<br/>features redefine what's possible.</p><div className="future-cards">{[["♧","New Features","Enhanced capabilities and tools to simplify your organization's impact."],["♧","Community Tools","Better ways to engage, connect, and grow your community."],["⌁","Analytics","Powerful insights to measure and optimize your impact."]].map(([icon,title,text])=><article key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className="products-cta"><h2>Ready to <em>super</em>charge<br/>your AI Transformation<br/>process?</h2><div><Link to="/contact" className="light-button">Contact Us</Link><Link to="/contact" className="gold-button">Book a Free Consultation Call <ArrowForwardIcon/></Link></div></section>
</main>; }
