import React from "react";
import { Link } from "react-router-dom";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import "./Services.css";

const offerings = [
  ["Application Development", "Custom software applications designed to meet your unique business requirements and drive digital transformation.", ["Tailored solutions that perfectly match your needs", "Scalable architecture for growth", "User-centric design for exceptional experiences", "Continuous support and maintenance"], "app"],
  ["Consulting Services", "Strategic guidance from industry experts to optimise your technology investments and improve business processes.", ["Expert analysis of your current technology landscape", "Strategic roadmaps for digital transformation", "Technology selection and implementation guidance", "Process optimisation recommendations"], "consult"],
  ["Advisory Services", "Insights and recommendations to help you navigate digital trends and make informed business decisions.", ["Industry trend analysis and insights", "Competitive landscape evaluation", "Risk assessment and mitigation strategies", "Innovation opportunity identification"], "advisory"],
];
const industries = [["Banking & Finance","photo-1556742049-0cfed4f6a45d"],["Healthcare & Life Sciences","photo-1576091160399-112ba8d25d1d"],["Financial Services","photo-1450101499163-c8848c66ca85"],["Manufacturing & Industrial","photo-1581092921461-eab62e97a780"],["Education & E-Learning","photo-1522202176988-66273c2fd55f"],["Energy & Utilities","photo-1476610182048-b716b8518aae"]];

export default function Services() {
  return <main className="services-page">
    <section className="services-hero"><div className="network" /><div><h1>Our Services</h1><p>Comprehensive solutions to drive your digital success</p></div></section>
    <section className="philosophy services-wrap"><div className="coffee-pour"><div className="cup" /><div className="stream" /><div className="pot" /></div><div><h2>Our Service<br />Philosophy</h2><p>At Dwaith Infotech, we believe that technology should serve as an enabler for business success. Our services are designed with this philosophy at the core, focusing on delivering solutions that drive tangible business outcomes.</p><p>We take a collaborative approach, working closely with our clients to understand their unique challenges and objectives. This enables us to develop tailored solutions that address specific needs rather than offering one-size-fits-all options.</p></div></section>
    <section className="core-services services-wrap"><h2>Our Core Services</h2><p>Explore how we can help your business thrive with our comprehensive service offerings</p><div className="offerings">{offerings.map(([title, text, benefits, type], i) => <article className={`offering ${type}`} key={title}><div className="service-art"><span>{type === "app" ? "◈" : type === "consult" ? "Ctrl" : "◌"}</span></div><div className="offering-card"><h3>{title}</h3><p>{text}</p><b>Key Benefits:</b><ul>{benefits.map(item => <li key={item}>{item}</li>)}</ul></div></article>)}</div></section>
    <section className="ai-data"><div className="services-wrap"><div className="ai-data-copy"><h2>AI &amp; Data Services</h2><p>In today's data-driven world, organizations that effectively harness the power of AI and data analytics gain significant competitive advantages. Our specialised team of data scientists, engineers, and AI specialists delivers solutions that transform raw data into strategic assets.</p></div><div className="banana-art">◒</div><div className="data-cards">{[["▣","Data Engineering","Build reliable, scalable data pipelines and infrastructure to ensure your data is accessible, secure, and ready for analysis."],["〽","Machine Learning & AI","Leverage the power of machine learning and AI to unlock new capabilities and insights that drive business growth."],["▥","Data Analytics & Visualization","Transform raw data into clear, actionable insights through compelling visualisations and reports."]].map(([icon,title,text])=><article key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="partner-proof"><h2>Dwaith Infotech is a preferred partner for <em>Fortune 100<br />companies</em></h2><p>Engineered for the complex demands of global enterprises; merging cutting-edge AI<br />with governance, precision, operational resilience, and uncompromising accountability.</p><div>{[["◉","Obsessive Customer Focus","Relentlessly aligned to client success with unwavering commitment to excellence."],["◆","Proven Value Delivery","Proven track record of delivering tangible results that drive business transformation."],["✦","Industry Leading Expertise","Deep expertise across AI, software solutions, long-term vision and transformation."]].map(([icon,title,text])=><article key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="industries-serve services-wrap"><h2>Industries We Serve</h2><div>{industries.map(([title,id])=><article key={title} style={{backgroundImage:`linear-gradient(0deg,rgba(17,23,23,.75),transparent),url(https://images.unsplash.com/${id}?auto=format&fit=crop&w=500&q=80)`}}><span>{title}</span></article>)}</div></section>
    <section className="services-cta"><h2>Ready to <em>super</em>charge<br />your AI Transformation<br />process?</h2><div><Link to="/contact" className="light-button">Contact Us</Link><Link to="/contact" className="gold-button">Book a Free Consultation Call <ArrowForwardIcon /></Link></div></section>
  </main>;
}
